package my.interviews2017.leetcode;

public class ValidPalindrome {

	public static void main(String[] args) {
		String s = "A man, a plan, a canal: Panama";
		String p = "race a car";
		String z = "adA";
		long time = System.currentTimeMillis();
		System.out.println(isPalindrome(z));
		System.out.println(validPalindrome("abcdeedcbia"));
		System.out.println(validPalindrome("ezhcvjohmdvdmirolicyblpgrdcdrhnhmpywartuszaaufjggdbrsocwfw"
				+ "efslflplclltubpzocdqxcvcubxveqkosbrphmoqqlxjifmdumpbchbwxyaneernszgsrcgrbhzsastrmvjgsntvxicvnm"
				+ "kyjxcpgzfwlznuxrdlhrtwktpnfmkjqpugeavlayyhzevicsgzjydketwlrquqcukqyhzxkhrrtmmzfzqvpqmspkamkjgfblbdab"
				+ "ddkiepzwseeakddjszyeapgoznixdghlnrhxzgegtlzfrarmpkfmdeitlhxogprzoijwptousenhiezrfsfosehemdhfnapfquzqi"
				+ "cotafgjiwrsohhqybcvxysttxjbjxdfqyexibyfvxzywtssmsdmgjcyvljgykdgcyehfnnsoaexalrcqhirjhrmrzcyyzrslktrhx"
				+ "irfpwzhrgzlhgougvhulgybfemvpzqbnqlaxwbxsfqhyohsemnuzykpuyvxtogzeuhqsxsmlsshxdkgqynfhketiqmaumcrtgrlfe"
				+ "jjkeckvumefotlhvdhguglzjskzgavatxgzohnpdcqkuayljhuvklksjdmxghqzbomubzeweobzvxvkzfprbpgokncbggdrbrfles"
				+ "kxduugbzevhkkwrsefmyzcygqjofysmwwfujsiypmcobcrhufwvvyabmucgvhobjrwgeqxgxsntvntlocnrnlkpaywpntfpvsohnf"
				+ "iefyzpqfvpcwubyarfuztiutkbdzxramhmbswtwyqvkvqwqiollsebluefuhsliquvjnsdskiqtscmrweqxvubxidacpoqmckduml"
				+ "ewuditgqrkbggkljbqptmiqfghwxbysrggsczwthugkwykmtbvebdbtfepxxvmqrsrnwfctcodouayrbxsqosbfsxvfqhhscvdxvp"
				+ "oaligfxfimkibtsdluwqeghjxuiomkogqehcfzsjescopcssqqpvfejkqivtakfdgsberbvpkcpvpyztxdzfikwgryfimffklvool"
				+ "akxbwtatnixeltfgnlexemelrbsoybceetympurdhabnzcwnieywkalnmafeacgawfxiczkifxetwqjeylfahqfnlajlwsmetykie"
				+ "wdabsdopuuhoccoowliomgcpxvmtwzoswptzwkeutcpihhfezaapwdwckavdyrvkxghrqoymmtypokeztuucylmbcsccujmyivbgo"
				+ "qhxoswzoibxeujhjbckqtovbjldhoeclsjnnrnlbaigxwkwtqmdrtuhqkwxinzgsfqwrziknqsesmgsnpbfxtawrpdnfuyhiptnjg"
				+ "ftutwmhrsjvkbjhclzraojwzdredtjdwbmtbvqtkllwyapjfcbcidhfqdohaxpqmwcogfpbfrnowyozzniomopvcuiezthjhjzoie"
				+ "tqlnfljymeyiluhmmljplonghetegljiwuckrinyjieeconisbrcmobjssconvemclkpkflgnlbclqkcwwtabpymywpqbrcwoinjv"
				+ "umqoaqlozmhabahuqzetxcxpfhqpclduxtxwfouiistsgfowfbxyjoyvmmgproaiqelaxwfbqkeaaglgrpnoqjnsjmetsrhbyuzih"
				+ "anojmttaabifnxwwqdbkqlisnvmxhhkodnmxyemhbemgyixxfzrzidzckztvdttuqvvqrofrrdcojsngotsrtxxcjjhgymqgwljmw"
				+ "fufbniuenstjfibjkfqgqhhyfvqhvogfvicjubtkfyqlsshmuwelguuyjqthxjurckedpdbtbtdtsvkmbgfdhejouhfjeusfcridr"
				+ "uwswnymvuhxpijyqatwiqjptcokigzrunzzycgzfbydwfkjunsgneasfbofrzfthndvkzygsvzdldebpsgvvdfezarggffmvzxgem"
				+ "fhlrpanvsinzatnxlsegsgohtqwicaimvvcrrqecqsjppmeuzprsvkpcqnmvtmvbbhutyohebrndraqmnboqzemwzwgjdkgxyajgn"
				+ "ardaeturqtvsvnkpdopojluskcgprrybepdipidltqvhpumyososzxruimhrpzimbkdqryjdwljusqzerrdtawojzbrwyifvegbon"
				+ "aljsbnezhbprtshokkiiumerxjwpnueiqbenjxzrqxhtldtlcrqsiocsdaavcuasnhciykdkqrewdinluamktistjollnmnakhazp"
				+ "hyhiunccziaaljawvykcsrrgvoocwonhdwmvyyavjytcgaggshsthcptqfbslcoxmulkrpzemcppeihsvylzocumigahkkmmursfk"
				+ "fxvqnhgiybaiyeknjlqyeqjscabggohazeukmrpmyffaerqhdiyaczlnidlwendgtipojfvyvqzpvuvmfruegmzouoijdbyikjjfz"
				+ "xntbseksqzgqtxpftxjirrqwjrzwcesjnqnyhnkyllyydhoqlmpazwdornuqeouunmqitwhyabkrzswwaoygvjptzewycrsbdimnb"
				+ "nyuvunibtsqveydfgtvdryxltawymxilsowvwakwxhrqsvmqgevbahpymfrtyikntkkndpvfqgbssubpoirkeppunhipkqbruequv"
				+ "bdvwwjizagfrfucurarawvfhmpjjybxefnybfdyleqfnpbmrkylkkqqnoyzlvnylfbijkrnqmklxnbzjospammuudekykgyljiydd"
				+ "blxfnhxlqvzpczkqhirdpddzvzvehxsyegosgmhonxkljrruuugubylibergbvhazfpsmbxpjunxbynvbvmirmsybujnfgeqzowph"
				+ "fbskyofywfjxccanjnwrbmfnlaqflkpcueipbhmnfxiwrhioeyqdvuryytfhzuwqfkibhrlyrkjvpqmixlxyxxmmwlbrspcuubqsy"
				+ "bfjahulgjfyhitblumsofrrrqmncgkgadywwrmrckkgzwpowdzfraooqzbufdkrutgdgqemmxowstxbswepvmgmlvuyxcqhkozcym"
				+ "jzivrxxkcorqpiijdhbthqjarpdtvyypldqvkyyixvzdatgxlgmbqcaxcfpgwspipevltutduhqatolzmxsccyxynmydodkoxujgj"
				+ "fsogqmdbwxcnitaegqyxnddsgiqazexukvkxnxrcpraeyvhvcvjpyiltpzhxykoeilytbqyzhmweqlcunbvhjpqyhheorrelibude"
				+ "qtbqvvdziywytyrcxtprklkrfwodfdcgssppqhftqrzbfrttnojroelwwvbdfrkmibpmxsmvpgresixsvqsaiyemyvrnkvkrcfpms"
				+ "jbjmeymgdbcczqtdcfpxrepommjzmuhwsrbcjspczsyxlajzookmgakmzscaxixpjgnpqjcwodsljvmoobsdnvpsbmugmhvlncwkh"
				+ "jnavgaxsgohhvmjyisqnrwybvvwupijuvjfuaotlcacrlcyqsysvilbbzthhyvzdveqrpflgiwpschuaxqbwnqyhvuygducneaapc"
				+ "yobhflvwwrwkkjxptodjoywzjietkbizgmvpvofguyrfkynlsbpuipxjbraatgxdrgqbjhzksigbwaozcwugoxpeipzkmsrpxgwwx"
				+ "fpfyqrvpsqabyxjuwxmqkkuwerjqpkmtaoztkkxyavclcagrizohinolfugkwflbamoakgqmjvwqjvlkquelaaszgshwrlqpiirbcqnjjngvrjorwzjbuldmsrtupeyrxypfhhyftehjcobrktryyerbfxbnyfskqaakjehbsftercfinmcujzrexlsxoybafaqwxrdyxbonncxrhjmtrelvgudfkmeelvygcrbwfaxzgbxlauqeichxjwpyujjikdlwfckhkcvppceguafzrtbzalwglfjzrtegwhtoavxudabsrmuryubgeekckwiatzhtmtculnpcijzglkbzyaiedxdgvbnrkoukbjcrfusowhjvvzxlucuoktwcbyjxhxtffusythvooigwgwprtnekupafidujzbpbmllpgiwtjeepljjwaldgapsoiarwqydllmdlhcnfaxmllgvitonfchtduicsqdwhsuewvgjkxbmeuvjmdluysuzkajbqasgibjjvghtjhxmreycmsqedumkiqvpgttwhnwtrxgwullrqqlfocfqmxopfvowmrzyxxkcjvaezqrsotydhszxddmocnjwftybzifonqsxruccezhhwyestmgpthfyxcuelomzacbdorjuqjcoqydeijsakiephbvtwccfkvkkzfumcsbumetodjsgpxwnnwfjtywtzunvnwkvqkyetnwpasjadfldagxgalqoqyzrngrfxejapmmcmlmivvkxcviecbdseuxsbdlpbulkafwrnltywxgchyupsjpfkxgozhbsqcotqshekudtofysxzchhegxuquohjhoqyvrwsbaqxbsvozedldbmvcutsealtrctwxowpkowfjpzjbaxixexealwjvuaxbswgeofabtgzglrivuvwochfyguuvrvdusxgoaeresmubqkxmljichkdzbuwtlyngpjnsdocrrmsphxxptkpmvuhognqqtmopbrxavftkfbbyivpfcehstgqncvixllvcqtjuanfrifvmcqvsdgnotbqvbaocapzupnmtfkgarkjjiqfuohfpyvbpnitcvirmwbbmjebitlfkronvefxgbuzzqahzrsgsysyjauaunlfhclvagkpeohuwlkmlzqahbcfratkmuxofhqcjpxibftucscninykgsvrbqrrzmscskodeuhnvjzrauqiadfjsnibcbocbgtlhchxyzxcsyoojckcyltnqodnywbyzlplnlsesftfbplfkympbtcpjlgnimhfzjusmojjjmosittisomjjjomsujzfhmingljpctbpmykflpbftfseslnlplzybwyndoqntlyckcjooyscxzyxhchltgbcobcbinsjfdaiquarzjvnhuedokscsmzrrqbrvsgkynincscutfbixpjcqhfoxumktarfcbhaqzlmklwuhoepkgavlchflnuauajysysgsrzhaqzzubgxfevnorkfltibejmbbwmrivctinpbvypfhoufqijjkragkftmnpuzpacoabvqbtongdsvqcmvfirfnaujtqcvllxivcnqgtshecfpviybbfktfvaxrbpomtqqngohuvmpktpxxhpsmrrcodsnjpgnyltwubzdkhcijlmxkqbumsereaogxsudvrvuugyfhcowvuvirlgzgtbafoegwsbxauvjwlaexexixabjzpjfwokpwoxwtcrtlaestucvmbdldezovsbxqabswrvyqohjhouquxgehhczxsyfotdukehsqtocqsbhzogxkfpjspuyhcgxwytlnrwfaklubpldbsxuesdbceivcxkvvimlmcmmpajexfrgnrzyqoqlagxgadlfdajsapwnteykqvkwnvnuztwytjfwnnwxpgsjdotemubscmufzkkvkfccwtvbhpeikasjiedyqocjqujrodbcazmoleucxyfhtpgmtseywhhzeccurxsqnofizbytfwjncomddxzshdytosrqzeavjckxxyzrmwovfpoxmqfcoflqqrlluwgxrtwnhwttgpvqikmudeqsmcyermxhjthgvjjbigsaqbjakzusyuldmjvuembxkjgvweushwdqsciudthcfnotivgllmxafnchldmlldyqwraiospagdlawjjlpeejtwigpllmbpbzjudifapukentrpwgwgioovhtysufftxhxjbcwtkouculxzvvjhwosufrcjbkuokrnbvgdxdeiayzbklgzjicpnluctmthztaiwkckeegbuyrumrsbaduxvaothwgetrzjflgwlazbtrzfaugecppvckhkcfwldkijjuypwjxhciequalxbgzxafwbrcgyvleemkfdugvlertmjhrxcnnobxydrxwqafabyoxslxerzjucmnifcretfsbhejkaaqksfynbxfbreyyrtkrbocjhetfyhhfpyxryeputrsmdlubjzwrojrvgnjjnqcbriipqlrwhsgzsaaleuqklvjqwvjmqgkaomablfwkguflonihozirgaclcvayxkktzoatmkpqjrewukkqmxwujxybaqspvrqyfpfxwwgxprsmkzpiepxoguwczoawbgiskzhjbqgrdxgtaarbjxpiupbslnykfryugfovpvmgzibkteijzwyojdotpxjkkwrwwvlfhboycpaaencudgyuvhyqnwbqxauhcspwiglfprqevdzvyhhtzbblivsysqyclrcacltoaufjvujipuwvvbywrnqsiyjmvhhogsxagvanjhkwcnlvhmgumbspvndsboomvjlsdowcjqpngjpxixacszmkagmkoozjalxyszcpsjcbrswhumzjmmoperxpfcdtqzccbdgmyemjbjsmpfcrkvknrvymeyiasqvsxisergpvmsxmpbimkrfdbvwwleorjonttrfbzrqtfhqppssgcdfdowfrklkrptxcrytywyizdvvqbtqedubilerroehhyqpjhvbnuclqewmhzyqbtylieokyxhzptliypjvcvhvyearpcrxnxkvkuxezaqigsddnxyqgeatincxwbdmqgosfjgjuxokdodymnyxyccsxmzlotaqhudtutlvepipswgpfcxacqbmglxgtadzvxiyykvqdlpyyvtdprajqhtbhdjiipqrockxxrvizjmyczokhqcxyuvlmgmvpewsbxtswoxmmeqgdgturkdfubzqooarfzdwopwzgkkcrmrwwydagkgcnmqrrrfosmulbtihyfjgluhajfbysqbuucpsrblwmmxxyxlximqpvjkrylrhbikfqwuzhftyyruvdqyeoihrwixfnmhbpieucpklfqalnfmbrwnjnaccxjfwyfoyksbfhpwozqegfnjubysmrimvbvnybxnujpxbmspfzahvbgrebilybuguuurrjlkxnohmgsogeysxhevzvzddpdrihqkzcpzvqlxhnfxlbddyijlygkykeduummapsojzbnxlkmqnrkjibflynvlzyonqqkklykrmbpnfqelydfbynfexbyjjpmhfvwararucufrfgazijwwvdbvuqeurbqkpihnuppekriopbussbgqfvpdnkktnkiytrfmyphabvegqmvsqrhxwkawvwoslixmywatlxyrdvtgfdyevqstbinuvuynbnmidbsrcyweztpjvgyoawwszrkbayhwtiqmnuuoequnrodwzapmlqohdyyllyknhynqnjsecwzrjwqrrijxtfpxtqgzqskesbtnxzfjjkiybdjiouozmgeurfmvuvpzqvyvfjopitgdnewldinlzcayidhqreaffymprmkuezahoggbacsjqeyqljnkeyiabyighnqvxfkfsrummkkhagimucozlyvshieppcmezprklumxoclsbfqtpchtshsggagctyjvayyvmwdhnowcoovgrrsckyvwajlaaizccnuihyhpzahkanmnllojtsitkmaulnidwerqkdkyichnsaucvaadscoisqrcltdlthxqrzxjnebqieunpwjxremuiikkohstrpbhzenbsjlanobgevfiywrbzjowatdrrezqsujlwdjyrqdkbmizprhmiurxzsosoymuphvqtldipidpebyrrpgcksuljopodpknvsvtqruteadrangjayxgkdjgwzwmezqobnmqardnrbehoytuhbbvmtvmnqcpkvsrpzuemppjsqceqrrcvvmiaciwqthogsgeslxntaznisvnaprlhfmegxzvmffggrazefdvvgspbedldzvsgyzkvdnhtfzrfobfsaengsnujkfwdybfzgcyzznurzgikoctpjqiwtaqyjipxhuvmynwswurdircfsuejfhuojehdfgbmkvstdtbtbdpdekcrujxhtqjyuuglewumhsslqyfktbujcivfgovhqvfyhhqgqfkjbifjtsneuinbfufwmjlwgqmyghjjcxxtrstognsjocdrrforqvvquttdvtzkczdizrzfxxiygmebhmeyxmndokhhxmvnsilqkbdqwwxnfibaattmjonahizuybhrstemjsnjqonprglgaaekqbfwxaleqiaorpgmmvyojyxbfwofgstsiiuofwxtxudlcpqhfpxcxtezquhabahmzolqaoqmuvjniowcrbqpwymypbatwwckqlcblnglfkpklcmevnocssjbomcrbsinoceeijynirkcuwijlgetehgnolpjlmmhuliyemyjlfnlqteiozjhjhtzeiucvpomoinzzoywonrfbpfgocwmqpxahodqfhdicbcfjpaywllktqvbtmbwdjtderdzwjoarzlchjbkvjsrhmwtutfgjntpihyufndprwatxfbpnsgmsesqnkizrwqfsgznixwkqhutrdmqtwkwxgiablnrnnjslceohdljbvotqkcbjhjuexbiozwsoxhqogbviymjuccscbmlycuutzekopytmmyoqrhgxkvrydvakcwdwpaazefhhipctuekwztpwsozwtmvxpcgmoilwooccohuupodsbadweikytemswljalnfqhaflyejqwtexfikzcixfwagcaefamnlakwyeinwcznbahdrupmyteecbyosbrlemexelngftlexintatwbxkaloovlkffmifyrgwkifzdxtzypvpckpvbrebsgdfkatviqkjefvpqqsscpocsejszfcheqgokmoiuxjhgeqwuldstbikmifxfgilaopvxdvcshhqfvxsfbsoqsxbryauodoctcfwnrsrqmvxxpeftbdbevbtmkywkguhtwzcsggrsybxwhgfqimtpqbjlkggbkrqgtiduwelmudkcmqopcadixbuvxqewrmcstqiksdsnjvuqilshufeulbeslloiqwqvkvqywtwsbmhmarxzdbktuitzufraybuwcpvfqpzyfeifnhosvpftnpwyapklnrncoltnvtnsxgxqegwrjbohvgcumbayvvwfuhrcbocmpyisjufwwmsyfojqgyczymfesrwkkhvezbguudxkselfrbrdggbcnkogpbrpfzkvxvzboewezbumobzqhgxmdjsklkvuhjlyaukqcdpnhozgxtavagzksjzlgughdvhltofemuvkcekjjeflrgtrcmuamqitekhfnyqgkdxhsslmsxsqhuezgotxvyupkyzunmeshoyhqfsxbwxalqnbqzpvmefbygluhvguoghlzgrhzwpfrixhrtklsrzyyczrmrhjrihqcrlaxeaosnnfheycgdkygjlvycjgmdsmsstwyzxvfybixeyqfdxjbjxttsyxvcbyqhhosrwijgfatociqzuqfpanfhdmehesofsfrzeihnesuotpwjiozrpgoxhltiedmfkpmrarfzltgegzxhrnlhgdxinzogpaeyzsjddkaeeswzpeikddbadblbfgjkmakpsmqpvqzfzmmtrrhkxzhyqkucquqrlwtekdyjzgscivezhyyalvaegupqjkmfnptkwtrhldrxunzlwfzgpcxjykmnvcixvtnsgjvmrtsaszhbrgcrsgzsnreenayxwbhcbpmudmfijxlqqomhprbsokqevxbucvcxqdcozpbutllclplflsfewfwcosrbdggjfuaazsutrawypmhnhrdcdrgplbycilorimdvdmhojvchze"));
		System.out.println(System.currentTimeMillis()-time);
	}
	
	public static boolean validPalindrome(String s) {
		int i = 0, j = s.length()-1;
		while (i<j) {
			if (s.charAt(i) == s.charAt(j)) { // Keep going if first and last chars match
				i++;
				j--;
			} else { return (isPalindrome1(s, i, j-1) || isPalindrome1(s, i+1, j)); };  // If they don't match check if first+1 and last match or first and last-1 match
		}
		return true;
	}
	
	public static boolean isPalindrome1(String s, int i, int j) {
    if (s.isEmpty()) return true;
    while (i < j) {
      if (s.charAt(i) == s.charAt(j)) {
        i++;
        j--;
      } else {
        return false;
      }
    }
    return true;
  }
	
	//"A man, a plan, a canal: Panama"
	public static boolean isPalindrome(String s) {
		int i = 0, j = s.length()-1;
		while (i<j) {
			if (!(toLower(s.charAt(i)) >= 'a' && toLower(s.charAt(i)) <= 'z')) i++; // Convert to lower and check if left is not a character, then move right
			else if (!(toLower(s.charAt(j)) >= 'a' && toLower(s.charAt(j)) <= 'z')) j--; // Convert to lower and check if right is not a character, then move left
			else if (toLower(s.charAt(i)) == toLower(s.charAt(j))) { // If both ends match keep going
				i++;
				j--;
			} else return false;
		}
		return true;
	}

	public static char toLower(char c) {
		if (c >= 'A' && c <= 'Z') return (char)(c-'A'+'a');
		return c;
	}
}
